# Generated by Django 4.2.7 on 2023-12-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manimage',
            new_name='mainmage',
        ),
    ]
