# Generated by Django 4.2.7 on 2023-12-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='addess',
            new_name='address',
        ),
    ]
